currency/urls.py
from django.urls import path

from currency import views

urlpatterns = [
    path('currency/convert/', views.convert_currency, name='convert_currency'),
]

django_currency_converter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('index.urls')),
    path('', include('currency.urls')),
    path('admin/', admin.site.urls),
]

index/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('signup/', views.signup, name="signup"),    
    
    path('password_reset/', views.CustomPasswordResetFormView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="index/recovery/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="index/recovery/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="index/recovery/password_reset_complete.html"), name='password_reset_complete'),
    
    path('profile/', views.profile, name='profile'),
]

currency/models.py
from django.db import models

# Create your models here.

currency/forms.py
from django import forms

# dummy choices 
choices=INTEGER_CHOICES = [('', '')]

class CurrencyForm(forms.Form):
    source_currency_value = forms.DecimalField(label='Amount')
    source_currency_code = forms.CharField(label='From', widget = forms.Select(choices=INTEGER_CHOICES))
    target_currency_code = forms.CharField(label='To', widget = forms.Select(choices=INTEGER_CHOICES))


    def __init__(self, tuple_country_code, *args, **kwargs):
        # required to set the initial form drop down with choices
        self.tuple_country_code = tuple_country_code
        super(CurrencyForm,self).__init__(*args, **kwargs)

        self.fields['source_currency_code'].widget.choices = self.tuple_country_code
        self.fields['target_currency_code'].widget.choices = self.tuple_country_code

currency/views.py
from django.http import HttpResponse
from currency import forms
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import requests
import json

@login_required(login_url="/login")
def convert_currency(request):
    ''' convert the given amount to target country amount'''
    
    # calling API using requests lib
    api_request = requests.get("http://data.fixer.io/api/latest?access_key=40eac7a32ba84e0369830d99248246b7")
    currency_dict = json.loads(api_request.text)
    print(currency_dict)
    currency_rates_dict = currency_dict['rates']
    list_of_country_currency_code = [x for x in currency_rates_dict.keys()]
    tuple_of_country_codes = [tuple([x,x]) for x in list_of_country_currency_code]
    
    # initialize form with country currency code
    currency_form = forms.CurrencyForm(tuple_of_country_codes,request.POST or None)

    converted_currency = ""
    if request.method == "POST":
        # check sanitation
        if currency_form.is_valid():

            # values from the html input fields
            source_currency_code = currency_form.cleaned_data['source_currency_code']
            target_currency_code = currency_form.cleaned_data['target_currency_code']
            input_currency_value = currency_form.cleaned_data['source_currency_value']

            # get live amount of selected country 
            from_country_base_value = currency_rates_dict[source_currency_code]
            to_country_base_value = currency_rates_dict[target_currency_code]
            
            # logic to calculate the converted_currency
            converted_currency = (to_country_base_value / from_country_base_value) * float(input_currency_value)

            return render(request, 'currency/currency-index.html', {'currency_form':currency_form, 'converted_currency':converted_currency})

    # form initialization
    context = {
        'currency_form': currency_form,
        'converted_currency':converted_currency
    }
    return render(request, 'currency/currency-index.html', context)

currency/templates/currency/currency-index.html
{% extends 'index/base.html' %}
{% load static %}


{% load crispy_forms_tags %}

{% block content %}
    <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'currency/css/base.css'%}">

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>


    <section>
        <div class="container">


            <div class="row">
                <div class="card box-shadow m-2">
                    <div class="card-header text-center">
                        <h4>Currency converter preview </h4>
                    </div>

                    <form id="form" class="p-3" action="." method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-4 mb-0">
                                {{ currency_form.source_currency_value|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{ currency_form.source_currency_code|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-4 mb-0">
                                {{ currency_form.target_currency_code|as_crispy_field }}
                            </div>
                        </div>
                        {% if converted_currency %}
                        <div class="card col-6 p-0 m-auto">
                            <div class="card-header text-center">
                                <h5>Converted amount</h4>
                                    <h5>from <b>{{currency_form.source_currency_code.value}}</b> to
                                        <b>{{currency_form.target_currency_code.value}}</b></h5>
                            </div>
                            <div class="card-body">
                                {{converted_currency}}
                            </div>

                        </div>
                        {% endif %}



                        <hr class="hr-line-dashed">
                        <div class="form-footer text-center">
                            <input id="submit" type="submit" class="btn btn-primary" value="Convert" />
                        </div>

                    </form>

                </div>
            </div>

        </div>

    </section>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            if($('#id_source_currency_value').val()){
                $('#submit').attr('value', 'Converting...');

            }
        });
    });
</script>


{% endblock content %}